# Ejemplos timeDistributed



<div class="alert alert-block alert-info">
Inspirado en:
__[How to Use the TimeDistributed Layer for Long Short-Term Memory Networks in Python](https://machinelearningmastery.com/timedistributed-layer-for-long-short-term-memory-networks-in-python/)__
</div>


In [14]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
import numpy as np
# prepare sequence
length = 5
seq = np.array([i/float(length) for i in range(length)])
X = seq.reshape(len(seq), 1, 1)
y = seq.reshape(len(seq), 1)
# define LSTM configuration
n_neurons = length
n_batch = length
n_epoch = 1000
# create LSTM
model = Sequential()
model.add(LSTM(n_neurons, input_shape=(1, 1)))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
print(model.summary())
# train LSTM
model.fit(X, y, epochs=n_epoch, batch_size=n_batch, verbose=0)
# evaluate
result = model.predict(X, batch_size=n_batch, verbose=0)
print(X)
print(y)
for value in result:
    print('%.1f' % value)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_8 (LSTM)                (None, 5)                 140       
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 6         
Total params: 146
Trainable params: 146
Non-trainable params: 0
_________________________________________________________________
None
[[[ 0. ]]

 [[ 0.2]]

 [[ 0.4]]

 [[ 0.6]]

 [[ 0.8]]]
[[ 0. ]
 [ 0.2]
 [ 0.4]
 [ 0.6]
 [ 0.8]]
0.0
0.2
0.4
0.6
0.8


In [44]:
from numpy import array
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
# prepare sequence
length = 5
seq = array([i/float(length) for i in range(length)])
X = seq.reshape(1, length, 1)
y = seq.reshape(1, length)
# define LSTM configuration
n_neurons = length
n_batch = 1
n_epoch = 500
# create LSTM
model = Sequential()
model.add(LSTM(n_neurons, input_shape=(length, 1)))
model.add(Dense(length))
model.compile(loss='mean_squared_error', optimizer='adam')
print(model.summary())
# train LSTM
model.fit(X, y, epochs=n_epoch, batch_size=n_batch, verbose=0)
# evaluate
result = model.predict(X, batch_size=n_batch, verbose=0)
print(X)
for value in result[0,:]:
	print('%.1f' % value)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_26 (LSTM)               (None, 5)                 140       
_________________________________________________________________
dense_26 (Dense)             (None, 5)                 30        
Total params: 170
Trainable params: 170
Non-trainable params: 0
_________________________________________________________________
None
[[[ 0. ]
  [ 0.2]
  [ 0.4]
  [ 0.6]
  [ 0.8]]]
0.0
0.2
0.4
0.6
0.8


In [2]:
from numpy import array
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import TimeDistributed
from keras.layers import LSTM
# prepare sequence
length = 11
#seq = array([i/float(length) for i in range(length)])
seq = array([[  0,   0, 14], 
             [0.2, 0.3, 12], 
             [0.4, 0.6, 14], 
             [0.6, 0.9, 12], 
             [0.8, 1.1, 14], 
             [1.0, 1.3, 12], 
             [1.2, 1.5, 14], 
             [1.4, 1.7, 12], 
             [1.6, 1.9, 14], 
             [1.8, 2.1, 12], 
             [2.0, 2.3, 14]])

X = seq.reshape(1, length, 3)
y = seq.reshape(1, length, 3)
# define LSTM configuration
n_neurons = length
n_batch = 1
n_epoch = 1000
# create LSTM
model = Sequential()
model.add(LSTM(20, input_shape=(length, 3), return_sequences=True))
model.add(TimeDistributed(Dense(3)))
model.compile(loss='mean_squared_error', optimizer='adam')
print(model.summary())
# train LSTM
model.fit(X, y, epochs=n_epoch, batch_size=n_batch, verbose=0)
# evaluate
result = model.predict(X, batch_size=n_batch, verbose=0)
print(X)
print(result)
for value in result[0,:,0]:
	print('%.1f' % value)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 11, 20)            1920      
_________________________________________________________________
time_distributed_1 (TimeDist (None, 11, 3)             63        
Total params: 1,983
Trainable params: 1,983
Non-trainable params: 0
_________________________________________________________________
None
[[[  0.    0.   14. ]
  [  0.2   0.3  12. ]
  [  0.4   0.6  14. ]
  [  0.6   0.9  12. ]
  [  0.8   1.1  14. ]
  [  1.    1.3  12. ]
  [  1.2   1.5  14. ]
  [  1.4   1.7  12. ]
  [  1.6   1.9  14. ]
  [  1.8   2.1  12. ]
  [  2.    2.3  14. ]]]
[[[  0.74941337   0.99251264   8.82220459]
  [  1.00458193   1.25547361  11.01443672]
  [  1.04455888   1.29650378  11.35266876]
  [  1.05010903   1.30219126  11.39936924]
  [  1.05087197   1.30297112  11.40573025]
  [  1.05097592   1.3030771   11.40659332]
  [  1.05099022   1.30309165 

In [43]:
seq2 = array([[1, 1], [1.2, 1.3], [1.4, 0.6], [1.6, 0.9], [0.8, 1.2]])
X2 = seq.reshape(1, length, 2)
model.predict(X2, batch_size=n_batch, verbose=0)

array([[[ 0.02797817,  0.05717673],
        [ 0.18083747,  0.27187762],
        [ 0.3940286 ,  0.5844878 ],
        [ 0.61285895,  0.91837245],
        [ 0.79498917,  1.19486117]]], dtype=float32)